Ordering cols
millij/poi-object-mapper pull request #49
Opened 2023-10-03 08:37 UTC by HarshaM0211

Enhanced to specify the order of the columns at the annotation level.

User should specify the index (starts form 1) value of the column at annotations.

2023-10-04 13:08 UTC, Rupesh8844 commented on src/main/java/io/github/millij/poi/util/Spreadsheet.java
> +        if (beanType == null) {
[pp]  Instead of check with == we prefer Objects.isNull
  `if (Objects.isNull(beanType){
 //logic
 }`

2023-10-04 13:23 UTC, Rupesh8844 commented on src/test/java/io/github/millij/bean/Emp_indexed.java
> +
Please annotate class with `@Sheet`

2023-10-09 13:29 UTC, millij requested changes
Please use spaces instead of tabs.

2023-10-11 08:07 UTC, millij commented on src/main/java/io/github/millij/poi/util/Spreadsheet.java
Replace the Tabs with Spaces in this file please.

2023-10-11 09:24 UTC, HarshaM0211 commented
Modified the code and PR. Raised a new PR #53  (better readable) with same content.

2023-10-12 04:17 UTC, closed without merging